### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by apsdehal** [sdslabs/muzi-scanner-old#3]
In current state code is in messed up state without presence of any kind of object orientation and functions. Use functions to segregate code which has a unique and recurring purpose and encapsulate all of it in a class.

**Comment by GauthamGoli** [comment]
Using functions to segregate code makes sense to me, but encapsulating all of it in a class ? From an outer view, the program has three nested for loops , which obtains the data and writes it to a DB. 
Can you tell me a bit more about encapsulating in a class with this program in context?
