### ISSUE TITLE
Better handling of thumbnails and cover errors

### ISSUE THREAD

**Issue by apsdehal** [sdslabs/muzi-scanner-old#6]
Due to way the track object is collected [here](https://github.com/sdslabs/muzi-scanner/blob/master/scan.py#L52), sometimes due to bad track titles we fail to get the proper track object, which could have been gotten in the next loop of the track scan. Handle cases when we fail to get the track object and set some parameters in variables object which is to be checked to handle thumbnails properly.

**Comment by GauthamGoli** [comment]
#10
